export type Lang = 'pt' | 'en'

// Conteúdo bilíngue da landing. pt e en têm exatamente a mesma estrutura.
export const content = {
  pt: {
    nav: {
      howItWorks: 'Como funciona',
      squad: 'Squad',
      roadmap: 'Roadmap',
      pricing: 'Preços',
      waitlist: 'Lista de espera',
    },
    hero: {
      badge: 'App mobile para devs · em desenvolvimento',
      titleLine1: 'Feito de dias',
      titleLine2: 'imperfeitos.',
      subtitle:
        'Cada commit que você faz vira streak, XP e rank. Compita com sua squad. Não quebre a ofensiva.',
      stats: [
        { label: '🔥', value: '23', sub: 'dias de ofensiva' },
        { label: '⚡', value: '1.4k', sub: 'XP esta semana' },
        { label: '🏆', value: '#2', sub: 'na sua squad' },
      ],
      emailPlaceholder: 'seu@email.com',
      cta: 'Entrar na lista →',
      ctaLoading: 'Entrando...',
      done: 'Você está na lista. Avisaremos quando lançar.',
      already: 'Esse email já está na lista.',
      error: 'Algo deu errado. Tenta de novo em instantes.',
      footnote: 'iOS · Android · sem spam.',
    },
    problem: {
      eyebrow: 'o problema',
      title: 'Você não é o problema.',
      sub: 'O problema é não ter nada em jogo quando você para.',
      items: [
        { title: 'O projeto esfriou', text: 'Você estava animado. Sumiu por uns dias. Quando voltou, o contexto foi embora junto. Recomeçar do zero toda vez drena mais do que o próprio trabalho.' },
        { title: 'Sem pressão externa, sem avanço', text: 'No trabalho tem prazo, tem time, tem cobrança. No projeto pessoal só tem você. E sem estrutura, a empolgação não dura mais do que duas semanas.' },
        { title: 'Comprometimento sem testemunhas', text: 'É fácil desistir quando ninguém sabe. Difícil é parar quando sua squad inteira vai ver que você quebrou a ofensiva de 47 dias.' },
        { title: 'Progresso invisível', text: 'Você trabalha, mas não vê crescer. Sem marcos, sem feedback visual, sem senso de conquista — parece que não sai do lugar.' },
      ],
    },
    howItWorks: {
      eyebrow: 'como funciona',
      titleLine1: 'Trabalha. O jogo',
      titleLine2: 'acontece sozinho.',
      sub: 'Não tem nada pra preencher. Só commitar.',
      steps: [
        { n: '01', title: 'Conecta o GitHub', body: 'Login com sua conta GitHub. O app passa a monitorar sua atividade — commits em qualquer repositório, público ou privado. Sem acesso de escrita, sem segredo.' },
        { n: '02', title: 'Commita. Normalmente.', body: 'Você trabalha como sempre. Quando o GitHub registra um commit seu, o momentum detecta automaticamente. Não tem botão pra apertar, não tem checklist manual.' },
        { n: '03', title: 'Sua ofensiva cresce', body: 'Cada dia com pelo menos 1 commit aumenta sua streak. Às 20h, se você ainda não commitou, chega uma notificação. Meia-noite sem commit — a ofensiva quebra.' },
        { n: '04', title: 'XP vira rank', body: 'Commits geram XP. XP acumulado na semana determina sua posição no ranking da squad. Domingo à noite: resultado. Top 3 sobem de rank. Nova semana começa na segunda.' },
        { n: '05', title: 'Personaliza, conquista, repete', body: 'Coins ganhas jogando desbloqueiam cosméticos. Streaks longas desbloqueiam itens lendários. Cada semana é uma nova rodada — nunca é tarde pra recuperar.' },
      ],
    },
    features: {
      eyebrow: 'o sistema',
      titleLine1: 'Quatro mecanismos.',
      titleLine2: 'Um hábito.',
      featuredTag: 'principal',
      items: [
        { num: '01', name: 'Ofensiva', role: 'retenção', featured: false, desc: 'Só ativa quando o GitHub confirma um commit seu. Não tem como fingir. Às 20h você recebe alerta se ainda não commitou. Meia-noite sem commit — streak quebra.' },
        { num: '02', name: 'XP e Rank', role: 'progressão', featured: true, desc: 'Commits geram XP. XP determina seu rank semanal. Seis ranks: Init → Build → Deploy → Senior → Architect → Legend. Top 3 da squad sobem todo domingo.' },
        { num: '03', name: 'Squad', role: 'social', featured: false, desc: 'Leaderboard em tempo real com seus amigos devs. Commits do dia, XP da semana, rank atual — tudo visível. Difícil parar quando a squad está olhando.' },
        { num: '04', name: 'Cosméticos', role: 'identidade', featured: false, desc: 'Seu avatar de dev pixel art, personalizável. Itens comuns com Coins ganhas jogando. Itens lendários só desbloqueados por conquistas reais — não são compráveis.' },
      ],
    },
    squads: {
      eyebrow: 'squad mode',
      titleLine1: 'Difícil parar quando',
      titleLine2: 'todo mundo tá olhando.',
      sub: 'Leaderboard semanal entre seus amigos. Rank sobe domingo. Nova rodada segunda.',
      week: 'semana 23 · termina em 2d 14h',
      live: 'ao vivo',
      youName: 'você',
      commitsXp: (c: number, xp: number) => `${c} commits · ${xp} XP`,
      lbFooter: 'top 3 sobem de rank no domingo',
      ranksTitle: 'sistema de ranks',
      youTag: 'você',
      rulesTitle: 'regras simples',
      rules: [
        '1 commit = ofensiva mantida + XP',
        'XP semanal = posição no ranking',
        'Top 3 sobem de rank todo domingo',
        'Streak freeze: 1/mês grátis · 3/mês Pro',
        'Grace period até 1h da manhã',
      ],
    },
    roadmap: {
      eyebrow: 'roadmap · o que vem aí',
      titleLine1: 'O hábito é só',
      titleLine2: 'o começo.',
      sub: 'Hoje o momentum transforma seus commits em ofensiva, XP e rank. O próximo passo é te ajudar a aprender de verdade — sem largar pela metade.',
      studyTag: 'próxima grande feature · em desenvolvimento',
      studyTitle: 'Modo Estudo',
      studyDesc: 'Trilhas das linguagens e conceitos que você escolhe aprender — no formato viciante que já provou que funciona, mas com a alma do momentum. Aprender vira ofensiva: estudou, ganhou XP, moeda e baú.',
      studyPoints: [
        'Trilhas de linguagens e conceitos — TypeScript, Rust, Go, algoritmos, sistemas…',
        'Cada lição concluída recompensa XP, moedas e baús',
        'Errar não pune: te traz de volta no dia seguinte',
        'Pixel art e HUD do momentum — nada de genérico',
      ],
      radarTitle: 'também no radar',
      radar: [
        { name: 'Liga competitiva', desc: 'Sprints de 2 semanas. Suba de tier ou caia.' },
        { name: 'Loja & baús', desc: 'Gaste moedas e gems. Abra baús por conquista.' },
        { name: 'Conquistas', desc: 'Marcos reais que desbloqueiam itens lendários.' },
        { name: 'Alertas inteligentes', desc: 'Um empurrão antes da meia-noite. Sem spam.' },
      ],
    },
    pricing: {
      eyebrow: 'preços',
      title: 'Simples e transparente.',
      sub: 'Comece grátis. Upgrade só quando sentir o valor.',
      perMonth: '/mês',
      free: 'Grátis',
      plans: [
        { name: 'Grátis', priceLabel: null, badge: null, desc: 'Para começar, sentir o jogo e manter a ofensiva antes de qualquer compromisso.', features: ['Streak verificada pelo GitHub', 'XP e ranking semanal', 'Squad com até 5 pessoas', '1 streak freeze por mês', 'Avatar com cosméticos básicos', 'Anúncios discretos (só na tela de resultado)'], cta: 'Entrar na lista de espera', primary: false },
        { name: 'Pro', priceLabel: 'Em breve', badge: 'no lançamento', desc: 'Para quem leva a sério e não quer nada no caminho.', features: ['Tudo do plano grátis', 'Sem anúncios', '3 streak freezes por mês', 'Squad ilimitada', 'Stats avançados e histórico completo', 'Acesso antecipado a cosméticos'], cta: 'Entrar na lista de espera', primary: true },
      ],
      disclaimer1: 'O plano pago chega no lançamento — preço ainda em definição.',
      disclaimer2: 'Começar é, e sempre será, de graça.',
    },
    faq: {
      eyebrow: 'perguntas frequentes',
      title: 'Tirar dúvidas.',
      items: [
        { q: 'Como a ofensiva é verificada?', a: 'O app conecta com sua conta GitHub via OAuth e monitora seus eventos de push. Quando você faz um commit em qualquer repositório — público ou privado — o momentum detecta automaticamente. Não tem como fingir: o commit precisa existir no GitHub.' },
        { q: 'Qualquer commit conta?', a: 'Sim, em qualquer repositório em que você seja o autor do commit. Merge de PR alheio não conta. Commits feitos até 1h da manhã ainda valem para o dia anterior — dev noturno é uma realidade.' },
        { q: 'O que é streak freeze?', a: 'Um salva-vidas para dias sem commit — viagem, doença, imprevisto. Ativa antes da meia-noite e sua ofensiva é preservada. Plano grátis tem 1 por mês. Pro tem 3.' },
        { q: 'Como funciona o sistema de ranks?', a: 'A semana começa na segunda e termina no domingo. Seu XP acumulado na semana determina sua posição no ranking da squad. No domingo à noite, os top 3 sobem de rank. Há seis ranks: Init → Build → Deploy → Senior → Architect → Legend.' },
        { q: 'O que é squad?', a: 'Um grupo de amigos ou colegas devs dentro do app. Vocês competem no mesmo leaderboard semanal. Você vê os commits, XP e rank de cada membro em tempo real. Plano grátis suporta squads de até 5 pessoas. Pro é ilimitado.' },
        { q: 'Como funcionam os cosméticos?', a: 'Seu avatar de dev pixel art é personalizável. Itens comuns e raros são comprados com Coins — moeda ganha jogando (streak, top 3, desafios). Itens lendários só desbloqueiam por conquistas reais, não são compráveis. Itens premium usam Gems, compradas com dinheiro real.' },
        { q: 'Tem anúncios?', a: 'No plano grátis, sim — mas só na tela de resultado semanal (domingo à noite). Nunca durante o uso normal do app. O plano Pro remove todos os anúncios.' },
        { q: 'Quando vai lançar?', a: 'Estamos construindo agora. Entre na lista de espera e você será avisado quando a primeira versão estiver disponível para iOS e Android. Sem spam — uma mensagem só.' },
      ],
    },
    finalCta: {
      titleLine1: 'Você não é o problema.',
      titleLine2: 'O processo é.',
      sub: 'Entre na lista de espera e seja avisado quando o app estiver pronto para download.',
      emailPlaceholder: 'seu@email.com',
      cta: 'Entrar na lista →',
      ctaLoading: '...',
      done: 'Você está na lista.',
      error: 'Algo deu errado. Tenta de novo em instantes.',
      footer: 'momentum · feito de dias imperfeitos.',
    },
  },

  en: {
    nav: {
      howItWorks: 'How it works',
      squad: 'Squad',
      roadmap: 'Roadmap',
      pricing: 'Pricing',
      waitlist: 'Waitlist',
    },
    hero: {
      badge: 'Mobile app for devs · in development',
      titleLine1: 'Built from',
      titleLine2: 'imperfect days.',
      subtitle:
        'Every commit you make turns into a streak, XP and rank. Compete with your squad. Don’t break the streak.',
      stats: [
        { label: '🔥', value: '23', sub: 'day streak' },
        { label: '⚡', value: '1.4k', sub: 'XP this week' },
        { label: '🏆', value: '#2', sub: 'in your squad' },
      ],
      emailPlaceholder: 'you@email.com',
      cta: 'Join the list →',
      ctaLoading: 'Joining...',
      done: 'You’re on the list. We’ll let you know at launch.',
      already: 'That email is already on the list.',
      error: 'Something went wrong. Try again in a moment.',
      footnote: 'iOS · Android · no spam.',
    },
    problem: {
      eyebrow: 'the problem',
      title: 'You’re not the problem.',
      sub: 'The problem is having nothing at stake when you stop.',
      items: [
        { title: 'The project went cold', text: 'You were pumped. Then you vanished for a few days. When you came back, the context was gone too. Starting over every time drains more than the work itself.' },
        { title: 'No external pressure, no progress', text: 'Work has deadlines, a team, accountability. A side project has only you. And without structure, the excitement rarely lasts more than two weeks.' },
        { title: 'Commitment with no witnesses', text: 'It’s easy to quit when no one knows. It’s hard to stop when your whole squad will see you broke a 47-day streak.' },
        { title: 'Invisible progress', text: 'You put in the work but don’t see it grow. No milestones, no visual feedback, no sense of achievement — it feels like you’re standing still.' },
      ],
    },
    howItWorks: {
      eyebrow: 'how it works',
      titleLine1: 'You work. The game',
      titleLine2: 'plays itself.',
      sub: 'Nothing to fill in. Just commit.',
      steps: [
        { n: '01', title: 'Connect GitHub', body: 'Sign in with your GitHub account. The app starts tracking your activity — commits in any repo, public or private. No write access, nothing sketchy.' },
        { n: '02', title: 'Commit. As usual.', body: 'You work like you always do. When GitHub records a commit of yours, momentum detects it automatically. No button to press, no manual checklist.' },
        { n: '03', title: 'Your streak grows', body: 'Each day with at least 1 commit grows your streak. At 8pm, if you haven’t committed yet, you get a nudge. Midnight with no commit — the streak breaks.' },
        { n: '04', title: 'XP becomes rank', body: 'Commits generate XP. Weekly XP sets your position in the squad ranking. Sunday night: results. Top 3 rank up. A new week starts on Monday.' },
        { n: '05', title: 'Customize, achieve, repeat', body: 'Coins earned by playing unlock cosmetics. Long streaks unlock legendary items. Every week is a new round — it’s never too late to bounce back.' },
      ],
    },
    features: {
      eyebrow: 'the system',
      titleLine1: 'Four mechanics.',
      titleLine2: 'One habit.',
      featuredTag: 'core',
      items: [
        { num: '01', name: 'Streak', role: 'retention', featured: false, desc: 'Only activates when GitHub confirms a commit of yours. No way to fake it. At 8pm you get an alert if you haven’t committed. Midnight with no commit — streak breaks.' },
        { num: '02', name: 'XP & Rank', role: 'progression', featured: true, desc: 'Commits generate XP. XP sets your weekly rank. Six ranks: Init → Build → Deploy → Senior → Architect → Legend. The squad’s top 3 rank up every Sunday.' },
        { num: '03', name: 'Squad', role: 'social', featured: false, desc: 'A real-time leaderboard with your dev friends. Today’s commits, weekly XP, current rank — all visible. Hard to stop when the squad is watching.' },
        { num: '04', name: 'Cosmetics', role: 'identity', featured: false, desc: 'Your pixel-art dev avatar, customizable. Common items with Coins earned by playing. Legendary items unlocked only by real achievements — not for sale.' },
      ],
    },
    squads: {
      eyebrow: 'squad mode',
      titleLine1: 'Hard to stop when',
      titleLine2: 'everyone’s watching.',
      sub: 'A weekly leaderboard among your friends. Ranks rise on Sunday. New round on Monday.',
      week: 'week 23 · ends in 2d 14h',
      live: 'live',
      youName: 'you',
      commitsXp: (c: number, xp: number) => `${c} commits · ${xp} XP`,
      lbFooter: 'top 3 rank up on Sunday',
      ranksTitle: 'rank system',
      youTag: 'you',
      rulesTitle: 'simple rules',
      rules: [
        '1 commit = streak kept + XP',
        'Weekly XP = leaderboard position',
        'Top 3 rank up every Sunday',
        'Streak freeze: 1/mo free · 3/mo Pro',
        'Grace period until 1am',
      ],
    },
    roadmap: {
      eyebrow: 'roadmap · what’s coming',
      titleLine1: 'The habit is just',
      titleLine2: 'the beginning.',
      sub: 'Today momentum turns your commits into a streak, XP and rank. The next step is helping you actually learn — without quitting halfway.',
      studyTag: 'next big feature · in development',
      studyTitle: 'Study Mode',
      studyDesc: 'Tracks for the languages and concepts you choose to learn — in the addictive format that already proved it works, but with momentum’s soul. Learning becomes a streak: study, earn XP, coins and chests.',
      studyPoints: [
        'Tracks for languages and concepts — TypeScript, Rust, Go, algorithms, systems…',
        'Every lesson completed rewards XP, coins and chests',
        'Mistakes don’t punish: they bring you back the next day',
        'Pixel art and momentum’s HUD — nothing generic',
      ],
      radarTitle: 'also on the radar',
      radar: [
        { name: 'Competitive league', desc: '2-week sprints. Climb a tier or drop.' },
        { name: 'Shop & chests', desc: 'Spend coins and gems. Open chests from achievements.' },
        { name: 'Achievements', desc: 'Real milestones that unlock legendary items.' },
        { name: 'Smart nudges', desc: 'A push before midnight. No spam.' },
      ],
    },
    pricing: {
      eyebrow: 'pricing',
      title: 'Simple and transparent.',
      sub: 'Start free. Upgrade only when you feel the value.',
      perMonth: '/mo',
      free: 'Free',
      plans: [
        { name: 'Free', priceLabel: null, badge: null, desc: 'To get started, feel the game and keep the streak before any commitment.', features: ['GitHub-verified streak', 'Weekly XP and ranking', 'Squad of up to 5 people', '1 streak freeze per month', 'Avatar with basic cosmetics', 'Subtle ads (results screen only)'], cta: 'Join the waitlist', primary: false },
        { name: 'Pro', priceLabel: 'Soon', badge: 'at launch', desc: 'For those who take it seriously and want nothing in the way.', features: ['Everything in Free', 'No ads', '3 streak freezes per month', 'Unlimited squad', 'Advanced stats and full history', 'Early access to cosmetics'], cta: 'Join the waitlist', primary: true },
      ],
      disclaimer1: 'The paid plan arrives at launch — pricing still to be defined.',
      disclaimer2: 'Getting started is, and always will be, free.',
    },
    faq: {
      eyebrow: 'frequently asked',
      title: 'Clear things up.',
      items: [
        { q: 'How is the streak verified?', a: 'The app connects to your GitHub account via OAuth and monitors your push events. When you commit to any repo — public or private — momentum detects it automatically. No way to fake it: the commit has to exist on GitHub.' },
        { q: 'Does any commit count?', a: 'Yes, in any repo where you’re the author of the commit. Merging someone else’s PR doesn’t count. Commits made up to 1am still count for the previous day — night-owl devs are real.' },
        { q: 'What is a streak freeze?', a: 'A lifesaver for days without a commit — travel, illness, the unexpected. Activate it before midnight and your streak is preserved. Free plan has 1 per month. Pro has 3.' },
        { q: 'How does the rank system work?', a: 'The week starts Monday and ends Sunday. Your weekly XP sets your position in the squad ranking. Sunday night, the top 3 rank up. There are six ranks: Init → Build → Deploy → Senior → Architect → Legend.' },
        { q: 'What is a squad?', a: 'A group of dev friends or colleagues inside the app. You compete on the same weekly leaderboard. You see each member’s commits, XP and rank in real time. Free plan supports squads of up to 5. Pro is unlimited.' },
        { q: 'How do cosmetics work?', a: 'Your pixel-art dev avatar is customizable. Common and rare items are bought with Coins — earned by playing (streaks, top 3, challenges). Legendary items unlock only through real achievements; they’re not for sale. Premium items use Gems, bought with real money.' },
        { q: 'Are there ads?', a: 'On the free plan, yes — but only on the weekly results screen (Sunday night). Never during normal use. The Pro plan removes all ads.' },
        { q: 'When does it launch?', a: 'We’re building it now. Join the waitlist and we’ll let you know when the first version is available for iOS and Android. No spam — just one message.' },
      ],
    },
    finalCta: {
      titleLine1: 'You’re not the problem.',
      titleLine2: 'The process is.',
      sub: 'Join the waitlist and get notified when the app is ready to download.',
      emailPlaceholder: 'you@email.com',
      cta: 'Join the list →',
      ctaLoading: '...',
      done: 'You’re on the list.',
      error: 'Something went wrong. Try again in a moment.',
      footer: 'momentum · built from imperfect days.',
    },
  },
}

// Tipo derivado da versão pt (en tem a mesma forma).
export type Content = typeof content.pt
