export type Lang = 'pt' | 'en';

// Dicionário do app. Começa pelas telas estáveis (onboarding); as telas das
// features MVP (squad, loja, conquistas, baús) entram aqui conforme forem feitas.
export const strings = {
  pt: {
    common: {
      retry: 'Tentar de novo',
    },
    auth: {
      subtitle: 'feito de dias imperfeitos.',
      body: 'Cada commit que você faz vira streak, XP e rank.\nCompita com sua squad. Não quebre a ofensiva.',
      connecting: 'Conectando…',
      continueGithub: 'Continuar com GitHub',
      hint: 'momentum vive dos seus commits',
      errorAuth: 'Falha na autorização do GitHub',
      errorGeneric: 'Não foi possível entrar',
      errorNoClient: 'GITHUB_CLIENT_ID não configurado (mobile/.env)',
      connected: 'conta conectada',
      githubConnected: 'GitHub conectado ✓',
      verified: 'conta verificada — pronto para começar',
      enter: 'Entrar no momentum →',
    },
    squad: {
      loading: 'carregando…',
      noSquadTitle: 'sem squad',
      noSquadSubtitle: 'Crie a sua ou entre com um código de convite.',
      createTitle: 'criar squad',
      namePlaceholder: 'nome da squad',
      create: 'Criar',
      joinTitle: 'entrar com código',
      codePlaceholder: 'código (ex: ABC-DEF)',
      join: 'Entrar',
      members: 'membros',
      weekRanking: 'ranking da semana',
      owner: 'líder',
      invite: 'Convidar',
      inviteTitle: 'código de convite',
      inviteHint: 'Compartilhe esse código — toque pra copiar.',
      copied: 'copiado!',
      noActivity: 'Ainda sem atividade esta semana.',
      leave: 'Sair da squad',
    },
    settings: {
      title: 'configurações',
      language: 'Idioma',
      appearance: 'Aparência',
      theme: 'Tema',
      dark: 'Escuro',
      light: 'Claro',
      lightSoon: 'modo claro em breve',
      account: 'Conta',
      logout: 'Sair da conta',
      version: 'versão',
    },
    challenges: {
      section: 'desafios do dia',
      claim: 'coletar',
      items: {
        commit_today: { label: 'Commit do dia', desc: 'Faça pelo menos 1 commit hoje' },
        commit_marathon: { label: 'Maratona', desc: 'Faça 5 commits hoje' },
        keep_streak: { label: 'Mantenha a chama', desc: 'Mantenha a ofensiva por 3 dias' },
      },
    },
    ranking: {
      title: 'ranking',
      tabUsers: 'devs',
      tabSquads: 'squads',
      members: 'membros',
      you: 'você',
      empty: 'Sem dados ainda.',
    },
    liga: {
      title: 'liga',
      sprint: 'sprint',
      endsIn: 'termina em',
      days: 'dias',
      day: 'dia',
      today: 'hoje',
      promotion: 'sobem de divisão',
      relegation: 'descem de divisão',
      you: 'você',
      xpEarned: 'xp no sprint',
      empty: 'Ninguém na sua liga ainda. Faça commits pra pontuar!',
      globalRanking: 'ranking global →',
      howItWorks: 'Ganhe XP no sprint de 2 semanas. Os melhores sobem de divisão, os últimos descem.',
      tiers: { 1: 'Bronze', 2: 'Prata', 3: 'Ouro', 4: 'Platina', 5: 'Diamante', 6: 'Mestre' } as Record<number, string>,
    },
    social: {
      friendsTitle: 'amigos',
      add: '+ adicionar',
      requests: 'convites recebidos',
      yourFriends: 'seus amigos',
      noFriends: 'Você ainda não tem amigos. Adicione pelo @usuário do GitHub.',
      accept: 'aceitar',
      remove: 'remover',
      pending: 'pendentes',
      sent: 'enviado',
      inviteTitle: 'adicionar amigo',
      searchPlaceholder: '@usuário do github',
      sendInvite: 'enviar convite',
      inviteHint: 'Digite o @usuário do GitHub. Se a pessoa já te convidou, a amizade é confirmada na hora.',
      feedTitle: 'feed',
      feedEmpty: 'Sem novidades ainda. Conquiste algo ou adicione amigos!',
      you: 'você',
      ev: {
        achievement: 'desbloqueou {x}',
        achievement_generic: 'desbloqueou uma conquista',
        challenge: 'concluiu um desafio do dia',
        liga: 'subiu para a divisão {x}',
        streak: 'chegou a {x} dias de ofensiva',
        levelup: 'subiu de nível',
        rankup: 'subiu de rank',
        chest: 'abriu um baú lendário',
        squad: 'entrou numa squad',
      },
      profile: {
        title: 'perfil',
        add: '+ adicionar',
        addFriend: '+ adicionar',
        friendsLabel: '✓ amigos',
        acceptInvite: 'aceitar convite',
        pendingLabel: 'convite enviado',
        inviteSquad: 'convidar squad',
        statCommits: 'commits',
        statStreak: 'ofensiva',
        statRecord: 'recorde',
        seeFull: 'ver perfil completo →',
        heatTitle: 'atividade · 13 semanas',
        recentTitle: 'atividade recente',
        recentEmpty: 'Nenhuma atividade recente.',
        notFound: 'Perfil não encontrado.',
      },
    },
    achievements: {
      title: 'conquistas',
      unlocked: 'desbloqueadas',
      locked: 'bloqueadas',
      items: {
        hello_world: { label: 'Olá, Mundo', desc: 'Seu primeiro commit' },
        prolific: { label: 'Prolífico', desc: '50 commits' },
        centurion: { label: 'Centurião', desc: '100 commits' },
        machine: { label: 'Máquina', desc: '500 commits' },
        code_legend: { label: 'Lenda do Código', desc: '1000 commits' },
        spark: { label: 'Faísca', desc: '7 dias de ofensiva' },
        two_weeks: { label: 'Quinzena', desc: '14 dias de ofensiva' },
        consistent: { label: 'Constante', desc: '30 dias de ofensiva' },
        half_century: { label: 'Meio Século', desc: '50 dias de ofensiva' },
        unstoppable: { label: 'Inabalável', desc: '100 dias de ofensiva' },
        year_of_fire: { label: 'Ano de Fogo', desc: '365 dias de ofensiva' },
        ascendant: { label: 'Ascendente', desc: '1000 XP acumulado' },
        veteran: { label: 'Veterano', desc: '5000 XP acumulado' },
        living_legend: { label: 'Lenda Viva', desc: '10000 XP acumulado' },
      },
    },
    shop: {
      title: 'loja',
      buy: 'comprar',
      owned: 'adquirido',
      equip: 'equipar',
      equipped: 'equipado',
      insufficient: 'saldo insuficiente',
      cats: { all: 'tudo', HAT: 'chapéu', SHIRT: 'roupa', GLASSES: 'óculos', ACCESSORY: 'acessório', BACKGROUND: 'fundo' },
      modes: { shop: 'loja', legendary: 'lendário', challenge: 'desafios' },
      locked: 'bloqueado',
      unlockedTag: 'desbloqueado',
      cond: {
        maxStreak: 'ofensiva de {x} dias',
        commits: '{x} commits',
        xp: '{x} XP acumulado',
        achievements: '{x} conquistas',
        challenges: '{x} desafios coletados',
      },
      items: {
        c1: 'Boné Dev', c2: 'Hoodie Clone', c3: 'Gorro Hacker', c4: 'Óculos Hack',
        c5: 'Planta de Mesa', c6: 'Teclado Mecânico', c7: 'Bucket Hat', c8: 'Polo Corp',
        c9: 'Jaleco Lab', c10: 'Mochila Git', c11: 'Capacete Espacial', c12: 'Caneca Dev',
        c13: 'Cachecol Binário', c14: 'Luvas Táticas', c15: 'Robô de Mesa', c16: 'Faixa de Antena',
        g1: 'Hoodie do Void', g2: 'Coroa de Dados', g3: 'Fundo Código Verde', g4: 'Headset Pro',
        g5: 'Manto do Void', g6: 'Armadura Neon', g7: 'Lâmina de Plasma', g8: 'Drone Vigília',
        g9: 'Fundo Circuito', g10: 'Fundo Cosmos', g11: 'Tiara Neural', g12: 'Cubo Quântico',
        g13: 'Escudo de Bits', g14: 'Bastão do Void',
        t1: 'Máscara Aracnídea', t2: 'Capuz do Cavaleiro', t3: 'Núcleo Arc', t4: 'Macacão 456',
        t5: 'Esfera de Captura', t6: 'Sabre Esmeralda', t7: 'Capacete Spartan', t8: 'Fundo Cidade Neon',
        ch1: 'Kit do Iniciante', ch2: 'Pato Depurador', ch3: 'Troféu de Ouro',
        ch4: 'Ampulheta Hacker', ch5: 'Robô de Batalha', ch6: 'Espada Binária',
      },
    },
    chests: {
      title: 'baús', open: 'abrir', empty: 'Sem baús no momento.',
      youGot: 'você ganhou', close: 'fechar',
    },
  },
  en: {
    common: {
      retry: 'Try again',
    },
    auth: {
      subtitle: 'built from imperfect days.',
      body: 'Every commit you make turns into a streak, XP and rank.\nCompete with your squad. Don’t break the streak.',
      connecting: 'Connecting…',
      continueGithub: 'Continue with GitHub',
      hint: 'momentum runs on your commits',
      errorAuth: 'GitHub authorization failed',
      errorGeneric: 'Couldn’t sign in',
      errorNoClient: 'GITHUB_CLIENT_ID not configured (mobile/.env)',
      connected: 'account connected',
      githubConnected: 'GitHub connected ✓',
      verified: 'account verified — ready to start',
      enter: 'Enter momentum →',
    },
    squad: {
      loading: 'loading…',
      noSquadTitle: 'no squad',
      noSquadSubtitle: 'Create yours or join with an invite code.',
      createTitle: 'create squad',
      namePlaceholder: 'squad name',
      create: 'Create',
      joinTitle: 'join with a code',
      codePlaceholder: 'code (e.g. ABC-DEF)',
      join: 'Join',
      members: 'members',
      weekRanking: 'this week',
      owner: 'owner',
      invite: 'Invite',
      inviteTitle: 'invite code',
      inviteHint: 'Share this code — tap to copy.',
      copied: 'copied!',
      noActivity: 'No activity yet this week.',
      leave: 'Leave squad',
    },
    settings: {
      title: 'settings',
      language: 'Language',
      appearance: 'Appearance',
      theme: 'Theme',
      dark: 'Dark',
      light: 'Light',
      lightSoon: 'light mode coming soon',
      account: 'Account',
      logout: 'Log out',
      version: 'version',
    },
    challenges: {
      section: "today's challenges",
      claim: 'claim',
      items: {
        commit_today: { label: 'Daily commit', desc: 'Make at least 1 commit today' },
        commit_marathon: { label: 'Marathon', desc: 'Make 5 commits today' },
        keep_streak: { label: 'Keep the flame', desc: 'Keep a 3-day streak' },
      },
    },
    ranking: {
      title: 'leaderboard',
      tabUsers: 'devs',
      tabSquads: 'squads',
      members: 'members',
      you: 'you',
      empty: 'No data yet.',
    },
    liga: {
      title: 'league',
      sprint: 'sprint',
      endsIn: 'ends in',
      days: 'days',
      day: 'day',
      today: 'today',
      promotion: 'promotion zone',
      relegation: 'relegation zone',
      you: 'you',
      xpEarned: 'xp this sprint',
      empty: 'Nobody in your league yet. Commit to score!',
      globalRanking: 'global ranking →',
      howItWorks: 'Earn XP over the 2-week sprint. Top players move up a division, the bottom move down.',
      tiers: { 1: 'Bronze', 2: 'Silver', 3: 'Gold', 4: 'Platinum', 5: 'Diamond', 6: 'Master' } as Record<number, string>,
    },
    social: {
      friendsTitle: 'friends',
      add: '+ add',
      requests: 'friend requests',
      yourFriends: 'your friends',
      noFriends: "You have no friends yet. Add by their GitHub @username.",
      accept: 'accept',
      remove: 'remove',
      pending: 'pending',
      sent: 'sent',
      inviteTitle: 'add friend',
      searchPlaceholder: 'github @username',
      sendInvite: 'send request',
      inviteHint: 'Enter a GitHub @username. If they already invited you, you become friends instantly.',
      feedTitle: 'feed',
      feedEmpty: 'Nothing here yet. Achieve something or add friends!',
      you: 'you',
      ev: {
        achievement: 'unlocked {x}',
        achievement_generic: 'unlocked an achievement',
        challenge: 'completed a daily challenge',
        liga: 'was promoted to division {x}',
        streak: 'reached a {x}-day streak',
        levelup: 'leveled up',
        rankup: 'ranked up',
        chest: 'opened a legendary chest',
        squad: 'joined a squad',
      },
      profile: {
        title: 'profile',
        add: '+ add',
        addFriend: '+ add',
        friendsLabel: '✓ friends',
        acceptInvite: 'accept invite',
        pendingLabel: 'request sent',
        inviteSquad: 'invite to squad',
        statCommits: 'commits',
        statStreak: 'streak',
        statRecord: 'record',
        seeFull: 'see full profile →',
        heatTitle: 'activity · 13 weeks',
        recentTitle: 'recent activity',
        recentEmpty: 'No recent activity.',
        notFound: 'Profile not found.',
      },
    },
    achievements: {
      title: 'achievements',
      unlocked: 'unlocked',
      locked: 'locked',
      items: {
        hello_world: { label: 'Hello, World', desc: 'Your first commit' },
        prolific: { label: 'Prolific', desc: '50 commits' },
        centurion: { label: 'Centurion', desc: '100 commits' },
        machine: { label: 'Machine', desc: '500 commits' },
        code_legend: { label: 'Code Legend', desc: '1000 commits' },
        spark: { label: 'Spark', desc: '7-day streak' },
        two_weeks: { label: 'Fortnight', desc: '14-day streak' },
        consistent: { label: 'Consistent', desc: '30-day streak' },
        half_century: { label: 'Half Century', desc: '50-day streak' },
        unstoppable: { label: 'Unstoppable', desc: '100-day streak' },
        year_of_fire: { label: 'Year of Fire', desc: '365-day streak' },
        ascendant: { label: 'Ascendant', desc: '1000 total XP' },
        veteran: { label: 'Veteran', desc: '5000 total XP' },
        living_legend: { label: 'Living Legend', desc: '10000 total XP' },
      },
    },
    shop: {
      title: 'shop',
      buy: 'buy',
      owned: 'owned',
      equip: 'equip',
      equipped: 'equipped',
      insufficient: 'not enough balance',
      cats: { all: 'all', HAT: 'hat', SHIRT: 'shirt', GLASSES: 'glasses', ACCESSORY: 'accessory', BACKGROUND: 'background' },
      modes: { shop: 'shop', legendary: 'legendary', challenge: 'challenges' },
      locked: 'locked',
      unlockedTag: 'unlocked',
      cond: {
        maxStreak: '{x}-day streak',
        commits: '{x} commits',
        xp: '{x} total XP',
        achievements: '{x} achievements',
        challenges: '{x} challenges claimed',
      },
      items: {
        c1: 'Dev Cap', c2: 'Clone Hoodie', c3: 'Hacker Beanie', c4: 'Hack Glasses',
        c5: 'Desk Plant', c6: 'Mech Keyboard', c7: 'Bucket Hat', c8: 'Corp Polo',
        c9: 'Lab Coat', c10: 'Git Backpack', c11: 'Space Helmet', c12: 'Dev Mug',
        c13: 'Binary Scarf', c14: 'Tactical Gloves', c15: 'Desk Robot', c16: 'Antenna Band',
        g1: 'Void Hoodie', g2: 'Data Crown', g3: 'Green Code Background', g4: 'Pro Headset',
        g5: 'Void Cloak', g6: 'Neon Armor', g7: 'Plasma Blade', g8: 'Vigil Drone',
        g9: 'Circuit Background', g10: 'Cosmos Background', g11: 'Neural Tiara', g12: 'Quantum Cube',
        g13: 'Bit Shield', g14: 'Void Staff',
        t1: 'Arachnid Mask', t2: 'Knight Cowl', t3: 'Arc Core', t4: 'Survival Suit 456',
        t5: 'Catch Sphere', t6: 'Emerald Saber', t7: 'Spartan Helmet', t8: 'Neon City Background',
        ch1: 'Starter Kit', ch2: 'Debug Duck', ch3: 'Gold Trophy',
        ch4: 'Hacker Hourglass', ch5: 'Battle Robot', ch6: 'Binary Sword',
      },
    },
    chests: {
      title: 'chests', open: 'open', empty: 'No chests right now.',
      youGot: 'you got', close: 'close',
    },
  },
} as const;
