export type Lang = 'pt' | 'en';

// Dicionário do app. Começa pelas telas estáveis (onboarding); as telas das
// features MVP (squad, loja, conquistas, baús) entram aqui conforme forem feitas.
export const strings = {
  pt: {
    common: {
      retry: 'Tentar de novo',
    },
    auth: {
      subtitle: 'feito de dias imperfeitos.',
      body: 'Cada commit que você faz vira streak, XP e rank.\nCompita com sua squad. Não quebre a ofensiva.',
      connecting: 'Conectando…',
      continueGithub: 'Continuar com GitHub',
      hint: 'momentum vive dos seus commits',
      errorAuth: 'Falha na autorização do GitHub',
      errorGeneric: 'Não foi possível entrar',
      errorNoClient: 'GITHUB_CLIENT_ID não configurado (mobile/.env)',
      connected: 'conta conectada',
      githubConnected: 'GitHub conectado ✓',
      verified: 'conta verificada — pronto para começar',
      enter: 'Entrar no momentum →',
    },
    squad: {
      loading: 'carregando…',
      noSquadTitle: 'sem squad',
      noSquadSubtitle: 'Crie a sua ou entre com um código de convite.',
      createTitle: 'criar squad',
      namePlaceholder: 'nome da squad',
      create: 'Criar',
      joinTitle: 'entrar com código',
      codePlaceholder: 'código (ex: ABC-DEF)',
      join: 'Entrar',
      members: 'membros',
      weekRanking: 'ranking da semana',
      owner: 'líder',
      invite: 'Convidar',
      inviteTitle: 'código de convite',
      inviteHint: 'Compartilhe esse código — toque pra copiar.',
      copied: 'copiado!',
      noActivity: 'Ainda sem atividade esta semana.',
      leave: 'Sair da squad',
    },
    settings: {
      title: 'configurações',
      language: 'Idioma',
      appearance: 'Aparência',
      theme: 'Tema',
      dark: 'Escuro',
      lightSoon: 'modo claro em breve',
      account: 'Conta',
      logout: 'Sair da conta',
      version: 'versão',
    },
  },
  en: {
    common: {
      retry: 'Try again',
    },
    auth: {
      subtitle: 'built from imperfect days.',
      body: 'Every commit you make turns into a streak, XP and rank.\nCompete with your squad. Don’t break the streak.',
      connecting: 'Connecting…',
      continueGithub: 'Continue with GitHub',
      hint: 'momentum runs on your commits',
      errorAuth: 'GitHub authorization failed',
      errorGeneric: 'Couldn’t sign in',
      errorNoClient: 'GITHUB_CLIENT_ID not configured (mobile/.env)',
      connected: 'account connected',
      githubConnected: 'GitHub connected ✓',
      verified: 'account verified — ready to start',
      enter: 'Enter momentum →',
    },
    squad: {
      loading: 'loading…',
      noSquadTitle: 'no squad',
      noSquadSubtitle: 'Create yours or join with an invite code.',
      createTitle: 'create squad',
      namePlaceholder: 'squad name',
      create: 'Create',
      joinTitle: 'join with a code',
      codePlaceholder: 'code (e.g. ABC-DEF)',
      join: 'Join',
      members: 'members',
      weekRanking: 'this week',
      owner: 'owner',
      invite: 'Invite',
      inviteTitle: 'invite code',
      inviteHint: 'Share this code — tap to copy.',
      copied: 'copied!',
      noActivity: 'No activity yet this week.',
      leave: 'Leave squad',
    },
    settings: {
      title: 'settings',
      language: 'Language',
      appearance: 'Appearance',
      theme: 'Theme',
      dark: 'Dark',
      lightSoon: 'light mode coming soon',
      account: 'Account',
      logout: 'Log out',
      version: 'version',
    },
  },
} as const;
