export type Lang = 'pt' | 'en';

// Dicionário do app. Começa pelas telas estáveis (onboarding); as telas das
// features MVP (squad, loja, conquistas, baús) entram aqui conforme forem feitas.
export const strings = {
  pt: {
    common: {
      retry: 'Tentar de novo',
    },
    auth: {
      subtitle: 'feito de dias imperfeitos.',
      body: 'Cada commit que você faz vira streak, XP e rank.\nCompita com sua squad. Não quebre a ofensiva.',
      connecting: 'Conectando…',
      continueGithub: 'Continuar com GitHub',
      hint: 'momentum vive dos seus commits',
      errorAuth: 'Falha na autorização do GitHub',
      errorGeneric: 'Não foi possível entrar',
      errorNoClient: 'GITHUB_CLIENT_ID não configurado (mobile/.env)',
      connected: 'conta conectada',
      githubConnected: 'GitHub conectado ✓',
      verified: 'conta verificada — pronto para começar',
      enter: 'Entrar no momentum →',
    },
    squad: {
      loading: 'carregando…',
      noSquadTitle: 'sem squad',
      noSquadSubtitle: 'Crie a sua ou entre com um código de convite.',
      createTitle: 'criar squad',
      namePlaceholder: 'nome da squad',
      create: 'Criar',
      joinTitle: 'entrar com código',
      codePlaceholder: 'código (ex: ABC-DEF)',
      join: 'Entrar',
      members: 'membros',
      weekRanking: 'ranking da semana',
      owner: 'líder',
      invite: 'Convidar',
      inviteTitle: 'código de convite',
      inviteHint: 'Compartilhe esse código — toque pra copiar.',
      copied: 'copiado!',
      noActivity: 'Ainda sem atividade esta semana.',
      leave: 'Sair da squad',
    },
    settings: {
      title: 'configurações',
      language: 'Idioma',
      appearance: 'Aparência',
      theme: 'Tema',
      dark: 'Escuro',
      lightSoon: 'modo claro em breve',
      account: 'Conta',
      logout: 'Sair da conta',
      version: 'versão',
    },
    challenges: {
      section: 'desafios do dia',
      claim: 'coletar',
      items: {
        commit_today: { label: 'Commit do dia', desc: 'Faça pelo menos 1 commit hoje' },
        commit_marathon: { label: 'Maratona', desc: 'Faça 5 commits hoje' },
        keep_streak: { label: 'Mantenha a chama', desc: 'Mantenha a ofensiva por 3 dias' },
      },
    },
    ranking: {
      title: 'ranking',
      tabUsers: 'devs',
      tabSquads: 'squads',
      members: 'membros',
      you: 'você',
      empty: 'Sem dados ainda.',
    },
    achievements: {
      title: 'conquistas',
      unlocked: 'desbloqueadas',
      locked: 'bloqueadas',
      items: {
        hello_world: { label: 'Olá, Mundo', desc: 'Seu primeiro commit' },
        prolific: { label: 'Prolífico', desc: '50 commits' },
        centurion: { label: 'Centurião', desc: '100 commits' },
        machine: { label: 'Máquina', desc: '500 commits' },
        code_legend: { label: 'Lenda do Código', desc: '1000 commits' },
        spark: { label: 'Faísca', desc: '7 dias de ofensiva' },
        two_weeks: { label: 'Quinzena', desc: '14 dias de ofensiva' },
        consistent: { label: 'Constante', desc: '30 dias de ofensiva' },
        half_century: { label: 'Meio Século', desc: '50 dias de ofensiva' },
        unstoppable: { label: 'Inabalável', desc: '100 dias de ofensiva' },
        year_of_fire: { label: 'Ano de Fogo', desc: '365 dias de ofensiva' },
        ascendant: { label: 'Ascendente', desc: '1000 XP acumulado' },
        veteran: { label: 'Veterano', desc: '5000 XP acumulado' },
        living_legend: { label: 'Lenda Viva', desc: '10000 XP acumulado' },
      },
    },
    shop: {
      title: 'loja',
      buy: 'comprar',
      owned: 'adquirido',
      equip: 'equipar',
      equipped: 'equipado',
      insufficient: 'saldo insuficiente',
      cats: { all: 'tudo', HAT: 'chapéu', SHIRT: 'roupa', GLASSES: 'óculos', ACCESSORY: 'acessório', BACKGROUND: 'fundo' },
      items: {
        c1: 'Boné Dev', c2: 'Hoodie Clone', c3: 'Gorro Hacker', c4: 'Óculos Hack',
        c5: 'Planta de Mesa', c6: 'Teclado Mecânico', c7: 'Bucket Hat', c8: 'Polo Corp',
        c9: 'Jaleco Lab', c10: 'Mochila Git', c11: 'Capacete Espacial', c12: 'Caneca Dev',
        c13: 'Cachecol Binário', c14: 'Luvas Táticas', c15: 'Robô de Mesa', c16: 'Faixa de Antena',
        g1: 'Hoodie do Void', g2: 'Coroa de Dados', g3: 'Fundo Matrix', g4: 'Headset Pro',
        g5: 'Manto do Void', g6: 'Armadura Neon', g7: 'Lâmina de Plasma', g8: 'Drone Vigília',
        g9: 'Fundo Circuito', g10: 'Fundo Cosmos', g11: 'Tiara Neural', g12: 'Cubo Quântico',
        g13: 'Escudo de Bits', g14: 'Bastão do Void',
      },
    },
    chests: {
      title: 'baús', open: 'abrir', empty: 'Sem baús no momento.',
      youGot: 'você ganhou', close: 'fechar',
    },
  },
  en: {
    common: {
      retry: 'Try again',
    },
    auth: {
      subtitle: 'built from imperfect days.',
      body: 'Every commit you make turns into a streak, XP and rank.\nCompete with your squad. Don’t break the streak.',
      connecting: 'Connecting…',
      continueGithub: 'Continue with GitHub',
      hint: 'momentum runs on your commits',
      errorAuth: 'GitHub authorization failed',
      errorGeneric: 'Couldn’t sign in',
      errorNoClient: 'GITHUB_CLIENT_ID not configured (mobile/.env)',
      connected: 'account connected',
      githubConnected: 'GitHub connected ✓',
      verified: 'account verified — ready to start',
      enter: 'Enter momentum →',
    },
    squad: {
      loading: 'loading…',
      noSquadTitle: 'no squad',
      noSquadSubtitle: 'Create yours or join with an invite code.',
      createTitle: 'create squad',
      namePlaceholder: 'squad name',
      create: 'Create',
      joinTitle: 'join with a code',
      codePlaceholder: 'code (e.g. ABC-DEF)',
      join: 'Join',
      members: 'members',
      weekRanking: 'this week',
      owner: 'owner',
      invite: 'Invite',
      inviteTitle: 'invite code',
      inviteHint: 'Share this code — tap to copy.',
      copied: 'copied!',
      noActivity: 'No activity yet this week.',
      leave: 'Leave squad',
    },
    settings: {
      title: 'settings',
      language: 'Language',
      appearance: 'Appearance',
      theme: 'Theme',
      dark: 'Dark',
      lightSoon: 'light mode coming soon',
      account: 'Account',
      logout: 'Log out',
      version: 'version',
    },
    challenges: {
      section: "today's challenges",
      claim: 'claim',
      items: {
        commit_today: { label: 'Daily commit', desc: 'Make at least 1 commit today' },
        commit_marathon: { label: 'Marathon', desc: 'Make 5 commits today' },
        keep_streak: { label: 'Keep the flame', desc: 'Keep a 3-day streak' },
      },
    },
    ranking: {
      title: 'leaderboard',
      tabUsers: 'devs',
      tabSquads: 'squads',
      members: 'members',
      you: 'you',
      empty: 'No data yet.',
    },
    achievements: {
      title: 'achievements',
      unlocked: 'unlocked',
      locked: 'locked',
      items: {
        hello_world: { label: 'Hello, World', desc: 'Your first commit' },
        prolific: { label: 'Prolific', desc: '50 commits' },
        centurion: { label: 'Centurion', desc: '100 commits' },
        machine: { label: 'Machine', desc: '500 commits' },
        code_legend: { label: 'Code Legend', desc: '1000 commits' },
        spark: { label: 'Spark', desc: '7-day streak' },
        two_weeks: { label: 'Fortnight', desc: '14-day streak' },
        consistent: { label: 'Consistent', desc: '30-day streak' },
        half_century: { label: 'Half Century', desc: '50-day streak' },
        unstoppable: { label: 'Unstoppable', desc: '100-day streak' },
        year_of_fire: { label: 'Year of Fire', desc: '365-day streak' },
        ascendant: { label: 'Ascendant', desc: '1000 total XP' },
        veteran: { label: 'Veteran', desc: '5000 total XP' },
        living_legend: { label: 'Living Legend', desc: '10000 total XP' },
      },
    },
    shop: {
      title: 'shop',
      buy: 'buy',
      owned: 'owned',
      equip: 'equip',
      equipped: 'equipped',
      insufficient: 'not enough balance',
      cats: { all: 'all', HAT: 'hat', SHIRT: 'shirt', GLASSES: 'glasses', ACCESSORY: 'accessory', BACKGROUND: 'background' },
      items: {
        c1: 'Dev Cap', c2: 'Clone Hoodie', c3: 'Hacker Beanie', c4: 'Hack Glasses',
        c5: 'Desk Plant', c6: 'Mech Keyboard', c7: 'Bucket Hat', c8: 'Corp Polo',
        c9: 'Lab Coat', c10: 'Git Backpack', c11: 'Space Helmet', c12: 'Dev Mug',
        c13: 'Binary Scarf', c14: 'Tactical Gloves', c15: 'Desk Robot', c16: 'Antenna Band',
        g1: 'Void Hoodie', g2: 'Data Crown', g3: 'Matrix Background', g4: 'Pro Headset',
        g5: 'Void Cloak', g6: 'Neon Armor', g7: 'Plasma Blade', g8: 'Vigil Drone',
        g9: 'Circuit Background', g10: 'Cosmos Background', g11: 'Neural Tiara', g12: 'Quantum Cube',
        g13: 'Bit Shield', g14: 'Void Staff',
      },
    },
    chests: {
      title: 'chests', open: 'open', empty: 'No chests right now.',
      youGot: 'you got', close: 'close',
    },
  },
} as const;
